prefix pdll: <http://lodpaddle.univ-nantes.fr/> 
prefix foaf: <http://xmlns.com/foaf/0.1/> 
prefix dbpprop: <http://dbpedia.org/property/> 
select ?name ?category
where { 
?a foaf:name ?name. 
?a pdll:CategoryLabel ?category.
?a  dbpprop:town        "NANTES".
?a  pdll:statut         "Public".
}ORDER BY ?category